### ISSUE TITLE
Times and associated rooms 

### ISSUE THREAD

**Issue by bendygirl** [Drupal4Gov/Drupal-GovCon-2015#108]
times and associated rooms do not show up when plotting sessions. 

Using Alison's session https://www.drupalgovcon.org/drupal-govcon-2015/sessions/features-absolute-beginners-drupal-7
edit> schedule info>Session Time Slot(s) only shows "none" it should have a date, time and room. 

The session shows a time and date when using the drag and drop function, and after any session has been added to a specific time and room, it populates into the session time slot.

Looks like a bug, but might be a feature?

**Comment by timwood** [comment]
@bendygirl as user 1 (admin) I can see the Session time slot(s) (rooms, dates and times) in that field. So might be a permission thing with regular users that have admin role.

**Comment by bendygirl** [comment]
No, those only now show up because I associated a session with a time slot and room. Then, the times show up.

**Comment by timwood** [comment]
But to plot sessions you use the drag and drop back-end thingy, right?

**Comment by bendygirl** [comment]
We can use that since this option seems to be unavailable. But the layout on the page for the drag and drop was a bit difficult to look at (for my old eyes). 

Using the drag and drop might be the only option at this point.

**Comment by timwood** [comment]
I believe the drag-and-drop scheduler thingy creates a "timeslot" when you drag a session onto a time and room. Each timeslots is a field collection entity and this is what shows in the session node edit form at edit> schedule info>Session Time Slot(s), which is why there are no options until you start dragging sessions in the drag-and-drop scheduler. Let's just try to use the drag-and-drop scheduler.

**Comment by bendygirl** [comment]
Ok, will try this.
