### ISSUE TITLE
bug on scheduling

### ISSUE THREAD

**Issue by bendygirl** [Drupal4Gov/Drupal-GovCon-2015#112]
can't plot anything for Room B on July 23rd at 1pm.

**Comment by timwood** [comment]
I thought I was onto something, but ended up not. Not sure what's causing this or how to fix.

**Comment by bendygirl** [comment]
@Nneka @alisonjo2786 @unn so, @timwood is heading out for vacation and we've still got this bug, preventing us from plotting two sessions.

Can any or all of you take a look and see what's up with it?

**Comment by jonraedeke** [comment]
When I try to drag a session on that timeslot, my console shows an error:
POST https://www.drupalgovcon.org/ajax/cod-schedule/update-session 503 (Service Temporarily Unavailable)

**Comment by timwood** [comment]
Oh good clue, @jonraedeke . When I do the release in a bit I'll look into it. Post back here if you find anything else out.

**Comment by jonraedeke** [comment]
https://www.drupal.org/node/2281453

Looks like it might be related. I'll try this in a bit.

**Comment by jonraedeke** [comment]
Seems like if that was it, all of them would break. Plus path looks fine.

**Comment by timwood** [comment]
Okay. Looking at the details for the post request to https://www.drupalgovcon.org/ajax/cod-schedule/update-session which fails with the 503 error I see the following post data:

> session=696&timeslot=281&timeroom=cod-events-schedule-sessions-116-26

Unfortunately timeslot 281 does not exist in the DB table field_data_field_event_timeslots. It thinks it exists because it wants to use that timeslot ID instead of "NEW" which is what you see when dragging a session to a date/time without an associated timeslot. **_function cod_schedule_update_session**_ (line 223 in profiles/cod/modules/contrib/cod_support/cod_schedule/cod_schedule.module) is the function which is failing due to non-existent timeslot ID.

So I'm not sure what the timeslot 281 artifact is or how to fix it. Anyone have ideas?

**Comment by jonraedeke** [comment]
Can we add a new timeslot that is 5min different and drag all the sessions to the new one?

**Comment by jonraedeke** [comment]
If you click on the arrow to edit the timeslot and try to save you get an AJAX error popup.

**Comment by bendygirl** [comment]
Would we even need to do that? We could do it at 12:59. 

Or, can we move all the ones there now, to the new time and THEN, delete 1pm and recreate it? Would that work for the database?

**Comment by timwood** [comment]
All possible solutions. Let's try one or more in a local environment. @jonraedeke do you have time now?

**Comment by jonraedeke** [comment]
@timwood Yep, I have time now. I will pull prod and try that.

**Comment by jonraedeke** [comment]
Ok, so it worked to create a new timeslot, but when I deleted the old one and edited the new one to be 1pm, some sessions vanished. Not sure where. I'm going to try dragging them out of the 1pm to the side first.

**Comment by jonraedeke** [comment]
That was local, btw.

**Comment by jonraedeke** [comment]
That worked great. Locally, I dragged the sessions off that time slot, deleted it and created the timeslot again and dragged them back on. I just hope we can find and fix the 2 sessions that were unscheduled previously. I will do this on the prod site.

**Comment by jonraedeke** [comment]
Done. @bendygirl sorry if we screwed up 2 of the scheduled items, but the corrupt timeslot is gone now.

**Comment by bendygirl** [comment]
Wow, what a work around!!

**Comment by timwood** [comment]
YAY Jon! You are my hero.

**Comment by timwood** [comment]
1pm on Friday is also all set.
