### ISSUE TITLE
Big SCHEDULE button on mobile since menu is hidden

### ISSUE THREAD

**Issue by jonraedeke** [Drupal4Gov/Drupal-GovCon-2015#127]
@timwood had the idea to add a big "Schedule" button on mobile like http://drupalcamppa.org/ .

I think we should replace the big ticket button on the homepage with a schedule link and add the schedule link to the upper right, keeping the ticket button there as well since there is no register/waitlist menu item. The upper right buttons are very visible on every page.

Need to design.

**Comment by jonraedeke** [comment]
@timwood @bendygirl Do we need a "My Schedule" link in the upper right too, or can that be a button on the Schedule page?

Maybe the schedule page need prominent "My Schedule" and "BoF Schedule" buttons. I do wish they were tabs. I suppose I could fake that. Thoughts?

**Comment by timwood** [comment]
@jonraedeke If we can have the My Schedule functionality ready, we could add it to the schedule page. Four buttons (fake tabs) at the top of the schedule page? Schedule, My Schedule, BoF Schedule and Floor Layouts (or some other wording).

**Comment by bendygirl** [comment]
Floor Layouts are on the lanyard. Will they also be necessary on the site?

On Mon, Jul 13, 2015 at 9:11 AM, Tim Wood notifications@github.com wrote:

> @jonraedeke https://github.com/jonraedeke If we can have the My
> Schedule functionality ready, we could add it to the schedule page. Four
> buttons (fake tabs) at the top of the schedule page? Schedule, My Schedule,
> BoF Schedule and Floor Layouts (or some other wording).
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/Drupal4Gov/Drupal-GovCon-2015/issues/127#issuecomment-120923115
> .

## 

Kirsten
http://uniongal.blogspot.com
Join Uniongal on Reddit http://www.reddit.com/r/Uniongal/

**Comment by cmndr-king** [comment]
Wouldn’t hurt to have them on the site as well.  I’ve added them to the HackPad for reference.

-James

---

James King, MLS, FSLA

http://about.me/cmndr_king

**Comment by timwood** [comment]
<img width="610" alt="screen shot 2015-07-13 at 11 48 37 am" src="https://cloud.githubusercontent.com/assets/91050/8653945/3e3a9b5e-2955-11e5-9c1a-7fb2c787b01b.png">

My Schedule is filtered by sessions flagged by the logged in user to be on their schedule. For anonymous it shows all the timeslots with empty sessions, not elegant, but should be fine. Also, there is no filter by session track, since it's a personalized schedule that shouldn't be needed and adds complication.
<img width="634" alt="screen shot 2015-07-13 at 11 48 23 am" src="https://cloud.githubusercontent.com/assets/91050/8653946/3e3c570a-2955-11e5-8486-baa6298aed86.png">

<img width="774" alt="screen shot 2015-07-13 at 11 48 52 am" src="https://cloud.githubusercontent.com/assets/91050/8653944/3e39d098-2955-11e5-8e3a-597fb9525c40.png">

**Comment by timwood** [comment]
Sorry, I think i meant those images to go into another task...

**Comment by jonraedeke** [comment]
Committed big homepage schedule button to dev.

![screen shot 2015-07-14 at 11 40 19 pm](https://cloud.githubusercontent.com/assets/2054715/8690410/26d0c550-2a82-11e5-989d-4a669d85754d.png)

**Comment by timwood** [comment]
Nice!
